name: Continuous integration

on: [pull_request, push]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Using Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.x
      - name: run install, build and test
        working-directory: frontend
        run: |
          cd frontend
          npm install
          npm run test
